### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by umar-ahmed** [pmndrs/env#1]
- [x] Duplicate light
- [x] Delete light
- [x] Light opacity
- [ ] Light textures
- [x] Gradient lights
- [x] Solo lights
- [ ] Outlines on lights when selected
- [ ] Export preview to .png
- [ ] Export equirectangular map to .png
- [ ] Export equirectangular map to .hdr
  - https://github.com/DerSchmale/io-rgbe
  - https://www.graphics.cornell.edu/~bjw/rgbe/rgbe.c
  - https://github.com/matheowis/threejs-canvas-save-as-hdr
  - https://github.com/enkimute/hdrpng.js
- [x] Ability to upload your own 3D model
- [ ] Ability to upload an existing base hdri (maybe from HDRI haven to start)
- [ ] Export to JSX
- [x] Look at 

https://user-images.githubusercontent.com/8302959/190028719-52c17f65-a47c-40fb-bf9a-496dcdcfd792.mp4

- [ ] Ability to blur lights https://twitter.com/arnputz/status/1569745316064231427
- [ ] Edit multiple lights at the same time https://twitter.com/timkevinoxley/status/1569740280038932482
- [ ] Gradient layer

**Comment by spencercap** [comment]
amazing 👏👏👏

**Comment by Luiginicoletti** [comment]
this is abbandoned or going on?

**Comment by umar-ahmed** [comment]
> this is abbandoned or going on?

Not abandoned, but a bit slower to make progress these days. 

I took a detour to learn WebGPU and I am waiting for Safari to release support unflagged later this year. When that happens, I'm going to revamp this project with the latest version of Three.js and finish the remaining roadmap items
